[tools]
uv = "0.5.29"
python = "3.12.9"

[env]
mise.file = ".env"
_.python.venv = ".venv"

[tasks.make-env]
description = "Make .env"
run = 'eval "echo \"$(cat .env.example)\"" > .env'
# https://github.com/docker/compose/issues/4081#issuecomment-660609867

[tasks.check-config]
description = "Check variables used in compose.yaml"
run = "cd environments/dev && docker compose config"

[tasks.build-no-chache]
description = "Build Image without cache"
run = "cd environments/dev && docker compose build --parallel --no-cache"

[tasks.build]
description = "Build Image"
run = "cd environments/dev && docker compose build --parallel"

[tasks.up]
description = "Start Container"
run = "cd environments/dev && docker compose up -d"

[tasks.down]
description = "Stop Container"
run = "cd environments/dev && docker compose down --volumes --remove-orphans"

[tasks.exec]
description = "Enter Container"
run = "cd environments/dev && docker compose exec {{option(name='service', default='core')}} bash"
# execute: mise run exec --service <name>
# runs: cd environments/dev && docker compose exec <name> bash
# execute: mise run exec
# runs: cd environments/dev && docker compose exec core bash

[tasks.ci]
description = "Run CI job"
depends = ["lint", "type-check", "test-coverage"]

[tasks.lint]
description = "Lint"
run = "poe lint"

[tasks.lint-fix]
description = "Lint fix"
run = "poe lint-fix"

[tasks.format]
description = "Format"
run = "poe format"

[tasks.test]
description = "Test"
run = "poe test"

[tasks.test-coverage]
description = "Test Coverage"
run = "poe test-coverage --cov-report=term-missing && coverage report --format=markdown"
wait_for = ["lint", "type-check"]

[tasks.test-module]
description = "Test Module"
run = "poe test-module"

[tasks.type-check]
description = "Type Check"
run = "poe type-check"
wait_for = ["lint"]

