name: python-template
services:
  core:
    build:
      args:
        - DEPLOY_TARGET=/app/
        - PYTHON_VERSION=3.12.9
        - UV_PROJECT_ENVIRONMENT_PATH=/usr/local
      context: ../../
      dockerfile: environments/dev/Dockerfile
    env_file:
      - ../../.env
    tty: true
    volumes:
      - type: bind
        source: ../../
        target: /app
# ホスト側のフォルダを一部除外したい場合は、以下のように設定の追記が必要
# 例）.venvを除外したいとき
#       - type: volume
#         source: exclude
#         target: /app/.venv
# volumes:
#     exclude: